algoritmo "ex07L2"
// Função :
// Autor :
// Data : 06/04/2024
// Seção de Declarações 
var
   num1,num2:inteiro
inicio
// Seção de Comandos 
   escreval("Digite um número:")
   leia(num1)
   escreval("Digire outro número:")
   leia(num2)
   se num1>num2 entao
      escreval("O número:",num1," é maior!")
   senao
      escreval("O número:",num2," é maior!")
   fimse
fimalgoritmo
